### ISSUE TITLE
add_event_detect

### ISSUE THREAD

**Issue by icyz** [bobrathbone/GPIOconverter#2]
Thanks for this project; it's been incredibly helpful!

I'm encountering an issue when attempting to execute the following code:
```
BUTTON_IN = 20
BUTTON_OUT = 16
BUTTON_BOUNCE_TIME = 2000
GPIO.add_event_detect(BUTTON_IN, GPIO.BOTH, callback=button_press, bouncetime=BUTTON_BOUNCE_TIME)
```

https://github.com/bobrathbone/GPIOconverter/blob/0d74d257be41e655a76fd479ba381c1f88e1f3e4/RPi/GPIO.py#L120

The code fails at this line:
https://github.com/bobrathbone/GPIOconverter/blob/0d74d257be41e655a76fd479ba381c1f88e1f3e4/RPi/GPIO.py#L133

With the following error message: 'bad event request'.

I've also tried:
```
def x():
    print('okkkkkk')

GPIO.add_event_detect(BUTTON_IN, GPIO.RISING, callback=x)
```

Any advice or suggestions would be greatly appreciated. Thanks!

**Comment by bobrathbone** [comment]
Can you please provide more information. What OS are you using (should be bookworm)?  What model Pi are you using? Are you using Python3 ?  Send me a copy of your test program. I tested with the following code. 

```
#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

def button_press(gpio):
    print("button ",gpio )

BUTTON_IN = 20
BUTTON_BOUNCE_TIME = 2000
GPIO.add_event_detect(BUTTON_IN, GPIO.BOTH, callback=button_press, bouncetime=BUTTON_BOUNCE_TIME)

while True:
    time.sleep(0.1)
  
```
The add event worked fine. 
By the way do you really want a 2-second bounce time? 50 to 300 ms should be fine.

**Comment by icyz** [comment]
Sure, you're right, sorry:
Python 3.11.2
Raspberry PI 5 bookworm

I've tried your code, and it works... so strange. It's strange that my code isn't working. Let me investigate a bit.

**Comment by bobrathbone** [comment]
Do you have any further comments on this issue otherwise I will close it as NO FAULT FOUND in seven days time.

**Comment by icyz** [comment]
serse

**Comment by icyz** [comment]
Everything is working correctly. I've done some more testing, but I haven't encountered anything. The issue was due to my own code. Thank you very much.
